Expose currentVersion and currentBuild
tbaranes/VersionTrackerSwift pull request #22
Opened 2019-03-28 22:07 UTC by rudedogg

`currentVersion` and `currentBuild` were inaccessible due to being internal.

2019-03-29 07:47 UTC, tbaranes approved these changes

2019-03-29 07:48 UTC, tbaranes requested changes
Thanks for the PR!
Can you just add an entry to the CHANGELOG?

2019-04-02 19:29 UTC, rudedogg commented
Sorry for the delay, I added a changelog entry.

2019-04-03 06:56 UTC, tbaranes approved these changes
Thanks again!

2019-04-03 06:57 UTC, merged